version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    networks:
      - 42-network

  wordpress:
    build: ./requirements/wordpress/
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ~/data/wordpress:/var/www/html
    networks:
      - 42-network

  nginx:
    build: ./requirements/nginx/
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ~/data/wordpress:/var/www/html
    networks:
      - 42-network

networks:
  42-network:
    driver: bridge
