version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/
    restart: on-failure
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - 42-network

  wordpress:
    build: ./requirements/wordpress/
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - 42-network

  nginx:
    build: ./requirements/nginx/
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - 42-network

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/chanhuil/data/mariadb"
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/chanhuil/data/wordpress"

networks:
  42-network:
    driver: bridge